- hosts: fortigate
   collections:
    - fortinet.fortios
   connection: httpapi
   vars:
    vdom: "root"
    fortigate_adminport: 80
    fortigate_sadminport: 443
   
   tasks:
   - name: Configure global attributes.
     fortios_system_dns:
      vdom:  "{{ vdom }}"
      system_dns:
        primary: "1.0.0.1"
