 - hosts: fortigate
   collections:
    - fortinet.fortios
   connection: httpapi
   vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443

   tasks:
     - name: Configure DNS
       fortios_system_dns:
         system_dns:
           primary: "1.1.1.1"
